### ISSUE TITLE
getFlexibleProductPosition throw an error

### ISSUE THREAD

**Issue by chesha1** [binance/binance-connector-js#383]
I deployed some applications on Cloudflare but encountered an error related to `getFlexibleProductPosition`.

```json
{
  "stack": "    at JSON.parse (<anonymous>)\n    at httpRequestFunction (index-cf.js:5041:27)\n    at async Object.fetch (index-cf.js:7880:22)",
  "name": "SyntaxError",
  "message": "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON",
  "timestamp": 1749032437268
}
```

Here is a minimal reproduction repository: https://github.com/chesha1/bn-getFlexibleProductPosition-reproduce

You can deploy it on Cloudflare with two secrets to reproduce the issue.

**Comment by dimitrisn442** [comment]
Hi @chesha1, this should have been fixed in the latest version as we now wrap `JSON.parse()` on a `try...catch` block. Feel free to open a new issue if you encounter any more problems.

**Comment by dimitrisn442** [comment]
This doesn't seem like a connector's issue, rather than Cloudlfare behaviour. Could you please wrap your code on a `try...catch` statement share your error?

**Comment by dimitrisn442** [comment]
I don't think is a Cloudflare issue, rather your API Key restricted to a subset of whitelisted IPs. You need to either force a static IP on Cloudflare and add it to the whitelisted IPs list, or use a proxy. BTW, for those kind of questions you can always use [Binance Dev Community](https://dev.binance.vision/).

**Comment by tw1t611** [comment]
I ran into the same problem. The issue is not solved. Also I get the error on testnet, where api key permissions cannot be set.
